source 'http://rubygems.org'

gem 'sinatra', '1.3.2'
gem 'sinatra-static-assets', '1.0.3'
gem 'thin'
gem 'websocket-rack', path: './local_gems/websocket-rack-master/'
gem 'wirble'
#gem 'data_mapper', '1.2.0'
#gem 'json', '1.6.5'

group :development do
  gem 'dm-sqlite-adapter', '1.2.0'
  gem 'sass'
  gem 'rubyzip'
end

#If you plan on deploying to Heroku, uncomment this group

#group :production do
#  gem 'dm-postgres-adapter'
#end
